{% set name = "darkdetect" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ca0750faaf6e43d0a311b67f8fed4ba33b5747877f06337709a4dbb634a515fe

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.2
    - pip
  run:
    - python >=3.2

test:
  imports:
    - darkdetect

about:
  home: https://github.com/albertosottile/darkdetect
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Detect OS Dark Mode from Python

extra:
  recipe-maintainers:
    - hoechenberger
