{% set name = "darkdetect" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfe2f6e9b4eedacf9d52e4b0af4295869ea18e848194469cee5aa78cd4980e4c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.2
    - pip
  run:
    - python >=3.2

test:
  imports:
    - darkdetect

about:
  home: https://github.com/albertosottile/darkdetect
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Detect OS Dark Mode from Python

extra:
  recipe-maintainers:
    - hoechenberger
